### ISSUE TITLE
Play button doesn't play but keeps asking to open music file in ubuntu 13.10

### ISSUE THREAD

**Issue by nieknooijens** [performous/composer#15]
As the description said, I can't play the song in ubuntu 13.10, master does compile but qaudiodecoder branch gives linker-errors.

**Comment by andor-pierdelacabeza** [comment]
I had to install both `libqt5multimedia5-plugins` to avoid opening the 'open file' dialog and `gstreamer0.10-plugins-ugly` to get it to play an mp3 file. I think those packages should be added to the requirements list...

**Comment by nieknooijens** [comment]
yeap but the latest version of phonon uses gstreamer 1.0
you also need phonon-backend-gstreamer and phonon4qt5

**Comment by andor-pierdelacabeza** [comment]
Oh! I compiled it on Debian 8.6, and it was using gstreamer 0.10, even having v1.0 available on the system...

**Comment by nieknooijens** [comment]
weird, on ubuntu 16.04 / 16.10 it automatically picks 1.0. they recently changed that in the latest qt release.

**Comment by jmonga-1675** [comment]
I'm getting the same error, I believe I have all the dependencies installed, this is for Ubuntu 20.04.

**Comment by wallheater** [comment]
I had this exact issue on Linux Mint (Ubuntu) 20.3. Resolved by installing `libqt5multimedia5-plugins` per [andor-pierdelacabeza](https://github.com/andor-pierdelacabeza)'s comment
