### ISSUE TITLE
Because we can: ANDROID build!

### ISSUE THREAD

**Issue by nieknooijens** [performous/composer#18]
![screenshot_2014-08-13-10-47-56](https://cloud.githubusercontent.com/assets/2794331/3903045/d1b395de-22c6-11e4-8973-7b08d5d93451.png)

since Qt can create android apps, I was like "why not"? and guess what? it works!!! (only thing that doesn't is right-click and the audio decoding)

https://www.dropbox.com/s/60t1cqyoqqkslb7/composer-android.apk

should I upload it to a new branch?

**Comment by nieknooijens** [comment]
I made a new build: 
somehow the playback-speed-settings don't seem to work.
In order to make it more touch-screen friendly I'm trying to change right-click into a long-press with 
#ifdef ANDROID tags around it, but i'm still unsuccessful at the moment.
the new QT 5.4 also seems to make the scroll-bars alot larger, it makes it easier to control, but also obstructs the view.

**Comment by Baklap4** [comment]
Closing this since it's not really an issue or so; Cool it can be build on android :)! If you have a pr for the ifdef ANDROID, feel free to add it as a pr 👍
