### ISSUE TITLE
pitch visualization has wrong horizontal scale

### ISSUE THREAD

**Issue by s09bQ5** [performous/composer#23]
The pitch visualization is too wide. And it's not just silence added at the end. Everything is scaled.
A test file (wave, 16 bits, mono, 44.1 kHz) with 1.6 seconds of silence and 1.6 seconds of music finishes playing before the cursor reaches the first visualized note at 3.2 seconds and a song (wave, 16 bits, stereo, 44.1 kHz) that has 245 seconds of sound followed by 17 seconds of silence has notes drawn up to 266 seconds.
Using Ogg Vorbis instead of Wave makes no difference.

I'm on commit 42f058a22348acb406c4dd2fdaaf85c9989cdce6

**Comment by s09bQ5** [comment]
That was an easy one:

-       audioQueue.setRateChannels(cc->sample_rate, cc->channels);
+       audioQueue.setRateChannels(m_rate, 2);

**Comment by tapio** [comment]
ping @Tronic

**Comment by mirabilos** [comment]
Bug and fix confirmed with latest git. Please apply.

Cc @Natureshadow to apply to the Debian package as well.

**Comment by Tronic** [comment]
Issue trackers are very useful in burying bug reports but it is nice to see that sometimes they also get dug up!
