### ISSUE TITLE
Playback error: Error playing audio!  Pins cannot connect due to not supporting the same transport (0x8004020266)

### ISSUE THREAD

**Issue by shyamalschandra** [performous/composer#24]
What to do when I import a music file?  Even the CBR files do not work.  What should I do?

**Comment by nieknooijens** [comment]
What version do you use? And on what platform? Regarding Windows: we have a new experimental build which fixes a lot of audio issues (but introduces new bugs ;-) ) you can find it here: https://www.dropbox.com/s/lmf2euoli5x0n6g/Composer-2.0.exe?dl=0

**Comment by shyamalschandra** [comment]
I tried it a number of times and the placement on the pitch is not very accurate.  How many years did you put into the creation of this tool? Thanks!

**Comment by shyamalschandra** [comment]
Are there other tools that do the same thing?

**Comment by nieknooijens** [comment]
again, we can't fix it unless we can reproduce your problem, therefore we need to have the exact version and the platform you're using.

the commit log goes back to Jan 4, 2011 so over 4 years of development has been put into composer.
for other tools please refer to: https://github.com/performous/performous/wiki/Creation-tools

**Comment by nieknooijens** [comment]
closed due to long inactivity.
