### ISSUE TITLE
Windows building instructions are missing

### ISSUE THREAD

**Issue by basisbit** [performous/composer#26]
the windows building / compiling instructions are missing in the documentation / the readme.md. would be great if you could add them for more developers to maybe try and join the project.

**Comment by nieknooijens** [comment]
well we should also move the wiki articles from here:
https://github.com/performous/performous/wiki/Composer
to the wiki on this repo. Unfortunately I don't build "on windows" but I do build "for windows" from a MXE cross-environment on linux. there are some cmake issues that need to be resolved though (avutil opt lib is not detected very well and the path has to be manually changed in config.hh which is generated by cmake).

**Comment by basisbit** [comment]
you could maybe set up travis-ci to "build on windows" using wine and then upload the latest build to some webserver using sftp.

**Comment by TobiX** [comment]
I might set up some MXE builds in the future on my Jenkins server...

**Comment by Baklap4** [comment]
Windows "build instructions" are added as of latest pr to the readme: #48 
But to elaborate: 
1. Install dependencies with vcpkg
2. Start Visual Studio
3. Wait for Visual studio to be done with generating cmake files
4. CTRL + SHIFT + B -> Build project
5. F5 -> Run project
