### ISSUE TITLE
Unable to compile latest git version on ubuntu 16.04.1 fatal error

### ISSUE THREAD

**Issue by ap1325** [performous/composer#27]
/home/bcode/composer/src/ffmpeg.cc:18:28: fatal error: /usr/include/x86_64-1-gnu/libavutil/opt.h: No such file or directory
After that building is aborted

On Ubuntu 16.04.1 the builder seems to be looking for the file opt.h in the location:
/usr/include/x86_64-1-gnu/libavutil/
In my system the file opt.h is located on:
/usr/include/x86_64-linux-gnu/libavutil/
So the difference is the name of one folder x86_64-1-gnu is the name of the folder where the builder is looking, versus x86_64-linux-gnu the name of the folder that really exists in my system.
Please fix acordingly the cmake config files so composer can be built on Ubuntu 16.04.1 systems.
I also noticed that there is already a program called composer on ubuntu repositories (the dependency manager for PHP) and that may be the reason composer is not a program available on ubuntu repositories. ¿Have you considered changing composer's name? maybe pfcomposer  or pcomposer.

I hope this information can help in any way. Thank you for your hard work.

**Comment by nieknooijens** [comment]
yes this is indeed a problem in the configuration scripts.

when you open the build dir/src/config.hh and change it to:
'// FFMPEG libraries use changing include file names... Get them from CMake.
'#define AVCODEC_INCLUDE <libavcodec/avcodec.h>
'#define AVFORMAT_INCLUDE <libavformat/avformat.h>
'#define AVRESAMPLE_INCLUDE <libavresample/avresample.h>
'#define SWSCALE_INCLUDE <libswscale/swscale.h>
'#define AVUTIL_INCLUDE <libavutil/avutil.h>
'#define AVUTIL_OPT_INCLUDE <libavutil/opt.h> //HACK to get AVOption class!
'#define AVUTIL_MATH_INCLUDE <libavutil/mathematics.h>

it will compile normally

**Comment by ap1325** [comment]
It compiled normally just as you said. Thank you very much, I can't wait to get some songs ready. ;)

**Comment by nieknooijens** [comment]
yeah it's an ugly workaround for now, I still need to find some time to fix the cmake scripts.

**Comment by ap1325** [comment]
Take your time, leaving this bug report open will help anybody trying to compile mean-while. Thank you.
