### ISSUE TITLE
Synth sound dies and does not come back even toggleing Synthesizer's check box

### ISSUE THREAD

**Issue by ap1325** [performous/composer#28]
## **Synth sound dies and does not come back even toggleing Synthesizer's check box**
I use ubuntu 16.04.1 with kxstudio repositories
The Synth keeps disconnecting and I have no way to get the sound back without restarting composer.

Please anyone using ubuntu 16.04.1 try to reproduce this to verify it as a bug.
 
My guess would be that the synth used for playback on composer panics very easy.
Only exiting composer and starting it again brings the synth's sound back, but the sound goes away again after one or two synth playbacks, and I see no panic button on composer to bring the synth's sound back on. 

It would be easy for me if on a jack patchbay like Catia I would have synth MIDI output coming out of composer so I can connect it to the synth of my choice (maybe TiMidity or Qsynth).
Or a menu item on composer with MIDI connection options for composer's synth playback.

On the other hand I don't know if synth outputs would bring extra issues to other users (maybe new users), like trying to fine tune a song using bad soundfonts (meaning out of tune soundfonts).

MIDI output would be very helpful for me, but its your call. A panic button to bring back the current synth would be very helpful if no MIDI output is possible.

Thank you for the time reading, and any thing you do regarding this issue.

**Comment by nieknooijens** [comment]
Haven't been able to reproduce this yet, not on 16.04 and not on 14.04, will try tonight on 16.10.

**Comment by ap1325** [comment]
As a surprise to me when I turned on my pc last night synth sound did not stop at all. Maybe a memory leak from other program gave me this behavior I will see how the synth works next time and will post any outcomes.

**Comment by ap1325** [comment]
I just tried again and indeed the synth stopped working again after playing about one minute.
but on performous synth playback works well. (I installed performous form performous repository). I am still using Ubuntu 16.04.1
One weird thing on Composer is that even if I lost sound on the synth's playback, if I click on the piano keys drawn on the left border of composer; the synth's keys make sound as if there was no problem with the synth at all.

I am using Cadence and ALSA audio reads snd-aloop daemon, started, ALSA MIDI Bridge is running, and PulseAudio is started and bridged to JACK

**Comment by nieknooijens** [comment]
does it also occur without JACK?

**Comment by ap1325** [comment]
Hi
I use Ubuntu 16.04.1 plus KXStudio repositories
Without JACK I get no sound at all on this system. I have to start jack first using an application called
Cadence to get any sound on this system.
ALSA and PulseAudio can be run after that, using JACK Bridges, but you can not run them if JACK is not On.

**Comment by ap1325** [comment]
I will try all options available on Cadence and see if the problem gets solved. I will take one day or two for it, and after that I will post the outcome.

**Comment by ap1325** [comment]
So far I noticed that only JACK and the PulseAudio bridge need to be running for composer synth to work, and also, the synth gets choked when it goes over the most short notes (=0.0500 s) which is the most small note size composer will allow.

I want to point out that as I was getting a song ready, I noticed that in some songs, the phrase endigns end in an acrobatic voice run, where the last note is the tail of a descending run; and you would need a more short note than (=0.0500 s) for the singer to have a chance at all of scoring a star on that note. That is because the hole note has to be filled up completely to score a star on it. Sometimes you hit that last note but if the note is drawn longer than needed you do not have a chance to fill up that note, because the run is going downwards not horizontally ¿Is it possible for you to allow shorter notes than (=0.0500) on composer? And if you do. Will those short notes keep choking synth playback on composer?

**Comment by nieknooijens** [comment]
well the reason why I'm asking this is because I run a default ubuntu setup with JACK installed, but in my case, it routes everything through pulseaudio first, and when I start JACK only then will it kill pulseaudio and setup a bridge. when running pulse without JACK the synth works perfectly fine here, both on 16.04 and 16.10. when I have JACK running it kills pulseaudio and I have no sound at all on composer.

**Comment by ap1325** [comment]
I need this setup because this computer is mainly used to make music and most applications I use need JACK engine running, and PulseAudio turned off to work in an optimized manner. Low latency is a must here.
I use Ardour a lot and lots of JACK based audio applications very often. When I was using Ubuntu Vanilla I had lots of problems regarding PulseAudio because it kept interfering with JACK.
I could uninstall PulseAudio from the system and see what happens. Would Composer connect to ALSA directly if PulseAudio is not present?

**Comment by ap1325** [comment]
I removed PulseAudio and I get no synth playback.
The good thing is that I get Audio playback using only ALSA.
If your synth is PulseAudio based, I will not get Synth playback in Composer on this system.
But if whenever you can in the future you code one ALSA MIDI output for Composer, I could use it as a workaround.
In JACK's patch bay I could route that MIDI output, to one of Timidity input ports (perhaps Timidity input port 0). Or I could even use any other softSynth, or hardware Synth out there.

**Comment by nieknooijens** [comment]
I understand low latency is a must, and I also record/mix audio on this machine. but I'm doing that just for hobby and therefore I don't need JACK all the time. only when I'm going to use music apps I enable it, killing pulseaudio in the process. this has only one drawback: the pulseaudio sink/source plugins for Jack don't work on my system, but ardour/mixxx/xine support jack natively so for my situation it's not a problem. your results may vary. I just wanted to know if the problem is directly related to composer's code or that it's just composer not handling a particular setup very well.

**Comment by ap1325** [comment]
I will figure a way (It may take some time because I have to find out how) to disable jack completely and work with pulseaudio only. I will let you know when I test that.

**Comment by ap1325** [comment]
I tried with JACK turned off, removed ~/.pulse folder, and logged off and on.
Without opening cadence, and JACK turned off, I run pavucontrol to make sure my USB interface was default for PulseAudio
The synth chocked just as before. No ALSA or JACK synth I have used in the past has chocked on this system, Composer's synth showed on pavucontrol as **QtPulseAudio:13312:** QtmPulseStream-13312-35100960
Audio playback is fine and showed on pavucontrol as **composer**: Playback Stream

**Comment by ap1325** [comment]
Same song on Performous plays Synth mode (ctrl + s) with no problems on the same system.

**Comment by ap1325** [comment]
Could you reproduce it using the same song files I am using? Here they are in a tar.gz file.
[Juan Luis Guerra.tar.gz](https://github.com/performous/composer/files/544467/Juan.Luis.Guerra.tar.gz)

**Comment by nieknooijens** [comment]
I can' t unfortunately:
https://www.dropbox.com/s/r0agyfo1p3jl44z/synth-test.ogv?dl=0

**Comment by ap1325** [comment]
Thank you for trying. If you can put a MIDI out on composer please do. As for this issue I think is time to close it.

**Comment by nieknooijens** [comment]
you can open a new issue "add midi output" with a detailed description.
I' ll add the label "enhancement" and put it on the roadmap.

**Comment by ap1325** [comment]
I already posted 'Please add midi output' thank you.

________________________________

**Comment by ap1325** [comment]
Thank you I will


________________________________
