### ISSUE TITLE
split syllabyles

### ISSUE THREAD

**Issue by Baklap4** [performous/composer#31]
Most of my time is using up to split the words into syllabyles. Why not just use a `-` as split marker for words while pasting the lyrics into composer. This will treat words as words, and split the words on `-` and remove the `-` from the word.

So following text:
`this bo-he-mi-an rhap-so-dy is frea-king awe-so-me`
would result into
`this bo he mi an rhap so dy is frea king awe so me`
where `bohemian`, `rhapsody`, `freaking` and `awesome` will result in one word with different notes.

**Comment by nieknooijens** [comment]
it already does that with un_der_sco_res

**Comment by Baklap4** [comment]
lmao i never knew alright closing this again

**Comment by Baklap4** [comment]
It was even on the wiki :fearful: https://github.com/performous/composer/wiki/importText
