### ISSUE TITLE
Problem with cursor while editing a song

### ISSUE THREAD

**Issue by MeadowValley** [performous/composer#34]
Okay, I was wrong with my first assume so I have to correct this issue completely.
I used a song with a length of 368 seconds and the editing area length matched with that.
But the cursor did not match with ANYTHING at all.
When i'd set it to the end of the song, it went out of editing area and the song was still playing for several seconds. Also when zooming in or out the cursor jumps to... somewhere?

**Comment by nieknooijens** [comment]
I have songs of 10 min+ (600 sec) which work perfectly fine.
what platform do you run and what version?

**Comment by DerKnecht** [comment]
I run it on windows 10 with the version which is promoted on performous.org.
I'm looking forward to give an explanation how to reproduce this.

**Comment by Baklap4** [comment]
Added `Can't Reproduce` as i can't reproduce this on latest master. Unfortunately we don't have an official release yet. Meanwhile you can try out this version: https://asgardsings.nl/composer-2.0.6.exe
