### ISSUE TITLE
Play button just opens the load music dialogue

### ISSUE THREAD

**Issue by mirabilos** [performous/composer#36]
commit beeea23502b5f21a623b8ddb494cbe67fc7c1947 (latest as of this writing)

If I click the Play button, it just always opens the dialogue to select a music file to load. (It then loads it and does lengthy processing, as indicated in the status bar.)

**Comment by mirabilos** [comment]
Also applies to V2.0 ☹

Perhaps my Qt 5.11.3 is just too new?

**Comment by mirabilos** [comment]
Surprisingly, it doesn’t even work with the below diff:

[x.txt](https://github.com/performous/composer/files/3587151/x.txt)

Apparently, the `currentMedia()` is always empty (debugging shows it to be `QUrl("")`)…

**Comment by mirabilos** [comment]
https://stackoverflow.com/q/45696232/2171120 someone else has the problem (the suggested answer doesn’t help)… looking into system configuration now.

**Comment by mirabilos** [comment]
switching from phonon4qt5-backend-vlc to phonon4qt5-backend-gstreamer does not solve this either

**Comment by mirabilos** [comment]
According to https://stackoverflow.com/a/22046880/2171120 the package `libqt5multimedia5-plugins` must be installed for Qt5 to produce audio. The already-extant debugging information was a great hint (no supported sample rates‽), but even *with* this package installed, it’s empty:

```
$ performous-composer                                                                        
qt5ct: using qt5ct plugin
qt5ct: D-Bus global menu: no
PulseAudioService: pa_context_connect() failed
Synth output format not supported, trying nearest
Synth output format not supported, trying nearest
QAudioDevice info
Supported codecs:
Supported sample rates:
Supported sample sizes:
Supported sample types:
Supported byte orders:
Supported channel counts:
Synth output format not supported, trying nearest
```

Playback works now, though…

**Comment by mirabilos** [comment]
Got that fixed, too…

    sudo dpkg-divert --rename \
      --divert /usr/lib/x86_64-linux-gnu/qt5/plugins/audio/libqtmedia_pulse.disabled \
      --add /usr/lib/x86_64-linux-gnu/qt5/plugins/audio/libqtmedia_pulse.so

Just deleting `/usr/lib/x86_64-linux-gnu/qt5/plugins/audio/libqtmedia_pulse.so` would also do the trick (until the next system update). Qt apparently provides no way to select the default audio backend at __run__time, and the pulse backend declares itself as “default”.

----

The dependency bug is now: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=939712

**Comment by Baklap4** [comment]
@mirabilos seems this is not an issue of ours then? Closing it for now, if you think otherwise please reopen this 👍

**Comment by mirabilos** [comment]
Yes, it’s at best a documentation issue.
