### ISSUE TITLE
Provide Windows binaries

### ISSUE THREAD

**Issue by twiecki** [performous/composer#51]
### Suggestion

Would be super useful to have windows binaries to install from.

### Use case

Any windows user that wants to use this but doesn't want to compile.

**Comment by Baklap4** [comment]
I do host a random build of 2.0.6 -> https://asgardsings.nl/composer-2.0.6.exe 
But we're actually looking to include builds through the CI just like on our main repository https://github.com/performous/performous

For this we're running into the same issue  https://github.com/performous/composer/issues/45#issuecomment-1373921848 as on fedora 37
Which we still need to address.

Closing this in favor of #42 as its a duplicate

**Comment by twiecki** [comment]
Thanks!
