### ISSUE TITLE
Co-Op-Project "FORMAT": Future of UltraStar TXT-Format

### ISSUE THREAD

**Issue by marwin89** [performous/composer#53]
### Suggestion

Dear Composer-Team, 👋 

in case you didn't heard of it - there is a new meta-project for all karaoke games just called "format".
Big Goal is to standardize and versionize the ultrastar txt-format (for every game, editor, tool, txt-file-hosting, usdbsyncer etc.).

Every developer of games, editors etc. can bring themselves in and shape the future of the format

GitHub: https://github.com/UltraStar-Deluxe/format
Website: https://usdx.eu/format

maybe you wanna watch the project or contribute sometimes. Everyone would be happy to have you on board as well. 🤝 

Its promising, it started in september and there are already important devs from different communites and software:
performous, melody mania, ultrastar deluxe, usdb-syncer, us manager, ultrasinger, usdb.animux etc.

There's is much consens and connection. Let's join forces and improve the format we all love together.

### Use case

We all need to standardize and versionize the ultrastar song format. Every game and song editor profits.

### Extra info/examples/attachments

![ultrastar-format-spec-website](https://github.com/performous/composer/assets/63517874/b0892da1-ac0e-4e0b-a4d2-36b7fcac9c08)
![ultrastar-format-spec-together](https://github.com/performous/composer/assets/63517874/8949f53a-b2f7-4524-98d1-3f0fb1a486c0)

**Comment by Baklap4** [comment]
The Performous team, which also looks out for Composer, will try to implement everything that's going on :) Thanks I thiknk this issue can be closed. Please - reopen if needed. Subsequent issues will be made to respect the spec file
